                             #/usr/bin/env python3
'............';a,b,c,d,e=[],[],sum,"".join(l.strip()for l in """;'............'


                          ..,;;:clllooooooollcc:;,..
                       .,:llllllooooooooooooooooooddol;.
                     .:lllllllooooooooooooooooooddddddddc.
                    .clllc''’  ;ooooooøooooooodddddddddddd,
                    'llll:      ;oooooooooooddddddddddddddd,
                    ,llll'      :oooooooooddddddddddddddddx,
                    ,olool.....cooooooooddddddddddddødddddx,
                    ,ooooooooooooooooooddddddddddddddddddxx,
                    ,ooooooooooooooddddddddddddddddddddxxxx,
                     ''''''''''''''''''cdddddddddXdddxxxxxx,
         .............,,,,,,,,,,,,,,,,,;ldddddddddddxxxxxxx,
     .,:lllllloooooooooooooooooodddddddddddddddøddxxxxxxxxx;   ,,,,,,,,,,
   .;lllllllooooooooooooooooooddddddddddddddddddxxxxxxxxxxx;   ,,,,;........
  .lllllllooooooooooøooooooooodddddddddddddddddxxxxxxxxxxxx;   ,,,,..........
 .lllllloooooooooooooooooooddddddddddddddddddxxxxxxxxxxxxøx,   ,,,;...........
.|lllloooooooooooooooooodddddddddddddddddddxxxxxxxxxxxxxxxx,   ,,,,............
.llløoooooooooooooooooooddddddøddddddddddddxxxxxxxxxxxxxxxc    ,,,;.............
;lloooooooooooooooooodddddddddddddddddddxxXxxxxxxxxxxxxxxc    ,,,,...............
cllòòoooooooooooooooddddddddddddddddxxxxxxxxxxxxxxxxxxxc.   ,,,,,;...............
llooooooooooooooooddddddddlc;;::::::::::::::::::::::,.    ,,,,,.................
oooooooooooooooooddddddøø..                              ,,,,,,;................
loooooooooooooodddddo,       ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;..................
coooooXoooooooodddddc,    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;....................
,oooooooooodddddddc    ,,,,,,,,,,,,,,,,,,X,,,,,,,,,,,,,,,.......................
.looooooooooþddddd.   ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...X.......................,
 .oooooodddddddddl.  ,,,,,,,,,,,,,‘,,,,,,,,,,,,,,,;...........................,
 .looodddddddddddl   ,‘,,,,,,,,,,,,,,,,,,,,,,,,,,...X.........................‘‘
  'ldddddddddddddl   ,,,,,,,,,,,,,,,,,,,,,,,,,’,...........................‘‘‘
    'odddddddddddo   ,,,,,,,,,,,,........................................‘‘‘
      ':cooddddddl   ;’.................................................‘‘
                     ...................
                     ....................      ,...........
                     ......................................
                     ......................................
                     ...........................      .....
                     ..........................        ....
                     ...........................      .....
                       ...........................  ......
                         ..............................
                             .......................
                                  ............

""")),'øøXøøøøX;øXXX‘X'
print(
    # DEBUG:
    ''.join(
        # switch X for l or i
        chr(X[2]) for X in
            [(
                a.append(d.find(j, sum(b,1))),
                b.append(a[i] - sum(b)),
                b[i])
             for i, j in
             # was: enumerate(e)
             zip(range(len(e)),e)
             ]
    )
)
#print(a)
#print(b)
print(list(zip(target, [ord(i) for i in target], b)))
