                             #/usr/bin/env python3
'............';a,b,c,d,e=[],[],sum,"".join(l.strip()for l in """;'............'

a,b,c,d,e=[],[],sum,''.join(filter(lambda ø:ø.strip(),"""



a,b,h,d,c,f=[],[],lambda j:(f(a)(d.index(j,c(b,24))),f(b)(a[-1]-c(b)),b[-1]),"".join("""

                           .,;;:clløøøøøøøX;ø‘::’:,..
                       .,:llllllooooooooooooooooooddol;.
                     .:lllllllooooooooooooooooooddddddddc.
                    .clllc''’  ;ooooooøooooooodddddddddddd,
                    'llll:      ;oooooooooooddddddddddddddd,
                    ,llll'      :oooooooooddddddddddddddddd,
                    ,olool.....cooooooooddddddddddddødddddx,
                    ,ooooooooooooooooooddddddddddddddddddxx,
                    ,ooooooooooooooddddddddddddddddddddxxxx,
                     ''''''''''''''''''cdddddddddødddxxxxxx,
         .............,,,,,,,,,,,,,,,,,;ldddddddddddxxxxxxx,
     .,:lllllloooooooooooooooooodddddddddddddddøddxxxxxxxxx;   ,,,,,,,,,,
   .;lllllllooooooooooooooooooddddddddddddddddddxxxxxxxxxxx;   ,,,,;........
  .lllllllooooooooooøooooooooodddddddddddddddddxxxxxxxxxxxx;   ,,,,..........
 .lllllloooooooooooooooooooddddddddddddddddddxxxxxxxxxxxxøx,   ,,,;...........
.|lllloooooooooooooooooodddddddddddddddddddxxxxxxxxxxxxxxxx,   ,,,,............
.llløoooooooooooooooooodddddddødddddddddddxxxxxxxxxxxxxxxxc    ,,,;.............
;lloooooooooooooooooodddddddddddddddddddxxXxxxxxxxxxxxxxxc    ,,,,...............
cllòòoooooooooooooooddddddddddddddddxxxXxXxxxxxxxxxxxxxc.   ,,,,,;...............‘
llooooooooooooooooddddddddlc;;::::::::::::::::::::::,.    ,,,,,,,.................
ooooooooooooooooddddøc,..                               ,,,,,,,;..................
loooooooooooooodddddø,       ,,,,,,,,,,,,;;;;;;;;;;;;,,,,,,,;....................‘‘
cooooooooooooooddddc,    ,,,,,,,,,,;;;;;;;;;;;;,,,,,,,,,,,,,.....................‘‘
,oooooooooodddddddc    ,,,,,,,,:;;;;;;;;;;;;;;,,,,,,,,,,,........................,
.loooooooodddddddd.   ,,,,,,;;;;;;;;;;;;;;;:,,,,,,,,,,,;........................‘,
 .oooooodddddddddl’   ,,,,,;;;;;;;;;;;;;;,,,,,,,,,,;............................‘,
 .looodddddddddddl   ,,,,;;;;;;;;;;;:,,,,,,,,,,,;..............................,
  'ldddddddddddddl   ,,,;;;;;;;;;;;;,,,,,,,,,;...............................‘‘
    'odddddddddddo   ,,,,,,,,,,,,...........................................‘
      ':cooddddddl   .....................................................‘
                     ...................
                     ....................      ............
                     ......................................
                     ......................................
                     ...........................      .....
                     ..........................        ....
                     ...........................      .....
                       ...........................  ......
                         ..............................
                             .......................
                                  ............
  
""".split()),sum,lambda a:a.append;e=d[8:23];print(''.join(chr(i[2])for i in map(h,e)))

#print(a)
#print(b)
