                             #/usr/bin/env python3
'............';a,b,c,d,e=[],[],sum,"".join(l.strip()for l in """;'............'


                          ..,;;:clllooooooollcc:;,..
                       .,:llllllooooooooooooooooooddol;.
                     .:lllllllooooooooooooooooooddddddddc.
                    .clllc''‘  ;oooooooooooooodddddddddddd,
                    'llll:      ;oooooooooooddddddddddddddd,
                    ,llll'      :oooooooooddddddddddddddddx,
                    ,olool.....cooooooooddddddddddddddddddx,
                    ,ooooooooooooooooooddddddddddddddddddxx,
                    ,ooooooooooooooddddddddddddddddddddxxxx,
                     ’’’‘‘‘‘‘‘‘‘‘‘‘‘‘‘‘‘cdddddddddddddxxxxx,
         .............,,,,,,,,,,,,,,,,,;ldddddddddddxxxxxxx,
     .,:lllllllooooooøøøøøøøøøø¤ddddddddddddddddddxxxxxxxxx;   ,,,,,,,,,,
   .;lllllllloooooooøøøøøøøøøøddddddddddddddddddxxxxxxxxxxx;   ,,,,;........
  .lllllllloooooooooooooooooodddddddddddddþddddxxxxxxxxxxxx;   ,,,,..........
 .lllllllloooooooooooooooooddddddddddddddddddxxxxxxxxxxxxxx,   ,,,;...........
 .|llllloooooooooooooooooddddddddddddddddddxxxxxxxxxxxxxxxx'   ,,,,...........
.lllllooooooooooooooooodddddddddddddddddddxxxx¤xxxxxxxxxxxc   ,,,;.............
;lllloooooooooooooooodddddddddddddddddddxxxxxxxxxxxxxxxxxc   ,,,,..............
cllòòøooooooooooooooddddddddddddddddddxxxxxxxxxxxxxxxxdc.   ,,,;................
llooooooooooooooooddddddddlc;;::::::::::::::::::::::,.    ,,,,,.................
ooooooooooooooooddddddo,..                              ,,,,,,;.................
loooooooooooooodddddo,       ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....................
cooooooooooooødddddc,    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;....................
,oooooooooodddddddc    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.......................
.looooooooooþddddd.   ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..........................,
 .oooooodddddddddl.  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,;...........................,
 .looodddddddddddl   ,,,,,,,,,,,,,,,,,,,,,,,,,,,............................‘‘
  'ldddddddddddddl   ,,,,,,,,,,,,,,,,,,,,,,,,,,...........................‘‘‘
    'odddddddddddo   ,,,,,,,,,,,;........................................’‘‘
      ':cooddddddl   ..................................................‘‘
                     ...................
                     ....................      ,...........
                     ......................................
                     ......................................
                     ...........................      .....
                     ..........................        ....
                     ...........................      .....
                       ...........................  ......
                         ..............................
                             .......................
                                  ............


""".splitlines()[1:]),'‘.‘¤ø.þ|¤ø:;ø.þ;‘.’,';print(''.join(chr(i[2]) for i in [(
a.append(d.find(j,c(b,i))),b.append(a[-1]-c(b,i)),b[i])for i,j in enumerate(e)]))
